
-- O % QUER DIZER QUE TEM MAIS CARACTERES, OU SEJA, ESTAR NO FINAL SIGNIFICA QUE A STRING CONTINUA APÓS, E ESTAR ANTES SIGNIFICA QUE TEM MAIS STRING ANTES.
-- FEZ SENTIDO?
--'LUCAS%' QUER DIZER "COMEÇA COM LUCAS E TEM OUTRAS COISAS APÓS" EXEMPLO 'LUCAS RENAN'
--'%LUCAS' QUER DIZER " TERMINA COM LUCAS E TEM OUTRAS COISAS ANTES" EXEMPLO 'JOÃO LUCAS'
--'%LUCAS%' QUER DIZER "EM ALGUM LUGAR NA STRING TEM A PALAVRA LUCAS" EXEMPLO 'HOJE A TARDE LUCAS TOMOU CAFÉ'



USE ContosoRetailDW

SELECT 
	FirstName + ' ' + LastName AS NOME,	
	*
FROM DimEmployee
-- RETORNA OS NOMES NO QUAL O SOBRENOME COMEÇA COM 'N'
--WHERE FirstName + ' ' + LastName LIKE '% N%'


-- RETORNA QUALQUER NOME QUE TENHA DOIS 'l' EM QUALQUER LUGAR DO NOME
--WHERE FirstName + ' ' + LastName LIKE '%ll%'

--QUALQUER NOME QUE TENHA 'i' OU 'y'
WHERE  FirstName + ' ' + LastName LIKE '%[iy]%'