
USE ContosoRetailDW

SELECT 
	 FS.channelKey AS CANAL_VENDA
	,FS.StoreKey AS LOJA
	,COUNT(SalesKey) AS TOTAL_VENDAS
	,MIN(SalesAmount) AS MINIMO
	,MAX(SalesAmount) AS MAXIMO
	,SUM(SalesAmount) AS TOTAL_VALOR_VENDAS

FROM FactSales AS FS
-- WHERE SEMPRE DEPOIS DO FROM E DEPOIS DO JOIN
WHERE FS.channelKey IN (2,3,4)
GROUP BY FS.channelKey, FS.StoreKey
--ORDER SEMPRE POR ULTIMO
ORDER BY FS.StoreKey