

USE ContosoRetailDW

SELECT TOP 5
	 FOS2.*
FROM FactOnlineSales FOS2
INNER JOIN(
	SELECT TOP 5
		 FOS.ProductKey CHAVE
		,SUM(FOS.SalesAmount) VALOR
	
	FROM FactOnlineSales FOS
	GROUP BY FOS.ProductKey
	ORDER BY VALOR DESC
) TOPPRODUTOS ON TOPPRODUTOS.CHAVE = FOS2.ProductKey


--SELECT SHOW DE EBOLA QUE USA 2 JOINS, UM DENTRO DE UMA SUBQUERY
--PARA TRAZER O FILTRO EM 2 TABELAS E OUTRO POR FORA PARA TRANSFORMAR
-- A SUBQUERY EM UMA TABELA PARA SER FILTRADO ENQUANTO TRAS O NOME DE PRODUTO DE OUTRA TABELA.
SELECT
	 FOS2.*
FROM FactOnlineSales FOS2
INNER JOIN(
	SELECT TOP 5
		 FOS.ProductKey CHAVE
		,DP.ProductName
		,SUM(FOS.SalesAmount) VALOR
	
	FROM FactOnlineSales FOS
	INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
	GROUP BY FOS.ProductKey, DP.ProductName
	ORDER BY VALOR DESC
) TOPPRODUTOS ON TOPPRODUTOS.CHAVE = FOS2.ProductKey


-- AGORA TUDO ACIMA VIRA UM SUBQUERY PARA UM FROM
SELECT 
	DISTINCT V.ProductKey
FROM(
	SELECT
		 FOS2.*
	FROM FactOnlineSales FOS2
	INNER JOIN(
		SELECT TOP 5
			 FOS.ProductKey CHAVE
			,DP.ProductName
			,SUM(FOS.SalesAmount) VALOR
	
		FROM FactOnlineSales FOS
		INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
		GROUP BY FOS.ProductKey, DP.ProductName
		ORDER BY VALOR DESC
	) TOPPRODUTOS ON TOPPRODUTOS.CHAVE = FOS2.ProductKey
) V