
USE ContosoRetailDW


/*
1- SET DATEFORMAT

MDY = MÊS/DIA/ANO. ESSE É O FORMATO AMERICANO. 
DMY = DIA/MÊS/ANO. ESSE É O FORMATO BRASILEIRO
YMD = ANO/MÊS/DIA.
YDM = ANO/DIA/MÊS.
MYD = MÊS/ANO/DIA.
DYM = DIA/ANO/MÊS.

*/

-- SET DATEFORMAT É USADO NO COMEÇO PARA JA DEIXAR O DADO NO FORMATO CORRETO PARA O SELECT.
SET DATEFORMAT YMD
SELECT DISTINCT
	FOS.DateKey

FROM FactOnlineSales FOS
WHERE FOS.DateKey BETWEEN '2008-01-01' AND '2008-12-31'
