

USE ContosoRetailDW

/*
DATEPART(PARTE, DATA)

VALOR				PARTE RETORNADA					ABREVIAÇÃO

YEAR				ANO								YY.YYYY
QUARTER				TRIMESTRE(1/4) DO ANO			QQ,Q
MONTH				MÊS								MM,M
DAYOFYEAR			DIA DO ANO						DY,Y
DAY					DIA								DD,D
WEEK				SEMANA							WK,WW
WEEKDAY				DIA DA SEMANA					DW
HOUR				HORA							HH
MINUTE				MINUTO							MI,N
SECOND				SEGUNDO							SS,S

*/



SELECT TOP(100)
	 FOS.DateKey
	,DATEPART(YEAR, DateKey) ANO
	,DATEPART(MONTH, DateKey) MES
	,DATEPART(DAYOFYEAR, DateKey) DIA_ANO
	,DATEPART(WEEK, DateKey) SEMANA
	,DATEPART(DAY, DateKey) DIA
	,DATEPART(WEEKDAY, DateKey) DIA_SEMANA
	
FROM FactOnlineSales FOS
ORDER BY FOS.DateKey DESC
--RETORNA O DIA DA SEMANA ATUAL
SELECT DATEPART(WEEKDAY, GETDATE()) DIA_DA_SEMANA

SELECT TOP(200)
	*
FROM FactOnlineSales
WHERE DAY(DateKey) BETWEEN 01 AND 15 AND
YEAR(DateKey) = 2008 AND 
UnitPrice <(SELECT AVG(UnitPrice) FROM FactOnlineSales)
