

USE ContosoRetailDW


SELECT TOP(200)
	*
FROM FactOnlineSales FOS
WHERE DAY(DateKey) BETWEEN 01 AND 15 AND
YEAR(DateKey) = 2008 AND 
UnitPrice <(SELECT AVG(UnitPrice) FROM FactOnlineSales)


SELECT TOP(100)
	 FOS.DateKey
/*	,DATEPART(YEAR, DateKey) ANO
	,DATEPART(MONTH, DateKey) MES
	,DATEPART(DAYOFYEAR, DateKey) DIA_ANO
	,DATEPART(WEEK, DateKey) SEMANA
	,DATEPART(DAY, DateKey) DIA
	,DATEPART(WEEKDAY, DateKey) DIA_SEMANA
*/	,DATENAME(DAY,DateKey) DIA
--DATENAME RETORNA O NOME DO DIA. EX; SEGUNDA-FEIRA
	,DATENAME(WEEKDAY, DateKey) DIASEMANAL
	,DATENAME(MONTH, DateKey) MES
--E AQUI RETORNA O NOME DO MÊS
	
FROM FactOnlineSales FOS
WHERE DATENAME(WEEKDAY,DateKey) = 'Segunda-Feira'
ORDER BY FOS.DateKey DESC


