

USE ContosoRetailDW



SELECT 
	 GETDATE() HOJE
	 --TRAS A DATA DE HOJE POREM 15 DIAS A FRENTE
	,DATEADD(DAY, 15, GETDATE()) DIA
	--TRAS A DATA DE HOJE POREM 2 MESES A FRENTE
	,DATEADD(MONTH, 2, GETDATE()) MES
	--TRAS A DATA DE HOJE, POREM 4 ANOS ATRAS
	,DATEADD(YEAR, -4, GETDATE()) ANO
	--TRAS A DATA DE HOJE POREM 12 HORAS ATRAS
	,DATEADD(HOUR, -12, GETDATE()) HORA