
DECLARE @USUARIO VARCHAR(25)
SET @USUARIO = 'Jeová Cleiton  '


SELECT @USUARIO NOME
	  ,LEN(@USUARIO) CARACTER
	  --LIMPA OS ESPAÇOS EM BRANCO DA ESQUERDA
	  ,RTRIM(@USUARIO) RTRIM
	  --LIMPA OS ESPAÇOS EM BRANCO DA DIREITA
	  ,LTRIM(@USUARIO) LTRIM
	  --MAIUSCULO
	  ,UPPER(@USUARIO) UP
	  --MINUSCULO
	  ,LOWER(@USUARIO) DOWN