
DECLARE @PALAVRA VARCHAR(35)
SET @PALAVRA = 'O pastel ta '


DECLARE @PALAVRA2 VARCHAR(35)
SET @PALAVRA2 = 'muito caro'


SELECT @PALAVRA + @PALAVRA2 FRASE_ALEATORIA

SELECT CONCAT(@PALAVRA, @PALAVRA2 + ' ' + 'meu nobre') FRASE