
SELECT
	'MEU CACHORRO É MAIS ENÉRGICO DO QUE MEU GATO'
	--SUBSTRING(TEXTO,PONTO DE INICIO, QUANTIDADE DE CARACTERES)
	,SUBSTRING('MEU CACHORRO É MAIS ENÉRGICO DO QUE MEU GATO',1, 3)
	--TRAS OS CARACTERES DA ESQUERDA
	,RIGHT('MEU CACHORRO É MAIS ENÉRGICO DO QUE MEU GATO', 8)
	--TRAS OS CARACTERES DA DIREITA
	,LEFT('MEU CACHORRO É MAIS ENÉRGICO DO QUE MEU GATO', 12)
	--AMBOS
	,LEFT(RIGHT('MEU CACHORRO É MAIS ENÉRGICO DO QUE MEU GATO',2), 2)
	--TRAS O INDICE NO QUAL COMEÇA A STRING PROCURADA
	,CHARINDEX('ALADO', 'CAVALO ALADO NÃO FICA PARADO')