--BASICAMENTE CRIA UMA TABELA TEMPORARIA COM OS DADOS JA AJUSTADOS PELOS SELECTS

WITH INFO_PRODUTOS(ANO, MES, PRODUTO, NOME, VENDAS_TOTAIS) AS (
SELECT
	 DATEPART(YEAR, FOS.DateKey) ANO
	,DATEPART(MONTH, FOS.DateKey) MES     
	,FOS.ProductKey PRODUTO
	,DP.ProductName NOME
	,SUM(FOS.SalesQuantity) VENDAS_TOTAIS
FROM FactOnlineSales FOS
INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
GROUP BY FOS.ProductKey, DP.ProductName, DATEPART(YEAR, FOS.DateKey),DATEPART(MONTH, FOS.DateKey)
)
SELECT 
	 AVG(VENDAS_TOTAIS) MEDIA_VENDA
	
FROM INFO_PRODUTOS
--ORDER BY ANO


WITH VENDA_ABAIXO_MEDIA(CHAVE, VENDA) AS (
	SELECT FS.ProductKey
		  ,FS.SalesAmount 
	
	FROM FactSales FS
	WHERE FS.SalesAmount <(SELECT AVG(SalesAmount) FROM FactSales)
)

SELECT 
	* 
FROM VENDA_ABAIXO_MEDIA
ORDER BY VENDA
