

WITH INFO_PRODUTOS(ANO, MES, PRODUTO, NOME, VENDAS_TOTAIS) AS (
SELECT
	 DATEPART(YEAR, FOS.DateKey) ANO
	,DATEPART(MONTH, FOS.DateKey) MES     
	,FOS.ProductKey PRODUTO
	,DP.ProductName NOME
	,SUM(FOS.SalesQuantity) VENDAS_TOTAIS
FROM FactOnlineSales FOS
INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
GROUP BY FOS.ProductKey, DP.ProductName, DATEPART(YEAR, FOS.DateKey),DATEPART(MONTH, FOS.DateKey)
)
SELECT TOP 10
	 --AVG(VENDAS_TOTAIS) MEDIA_VENDA
	*
FROM INFO_PRODUTOS
INNER JOIN DimProduct DP ON DP.ProductKey = INFO_PRODUTOS.PRODUTO
ORDER BY VENDAS_TOTAIS DESC
