

SELECT [TrackId]
      ,[Name]
	  ,[AlbumId]
      ,[Milliseconds]
      ,[UnitPrice]
	  -- AO USAR ROW_NUMBER COM PARTITION BY É POSSIVEL REMOVER DUPLICATAS, POIS ELE MARCA QUANTAS VESES ALGO SE REPETE
	  ,ROW_NUMBER() OVER(PARTITION BY  AlbumId ORDER BY UnitPrice) ROW_NUMBER_
	  --QUANDO O VALOR É IGUAL ELE REPETE O RANK
	  ,RANK() OVER(ORDER BY UnitPrice) RANK_
	  -- O MESMO POREM CONTINUA A CONTAGEM NORMAL
	  ,DENSE_RANK() OVER(ORDER BY UnitPrice) DENSE_RANK_
	  --,ROW_NUMBER() OVER(PARTITION BY Composer ORDER BY UnitPrice) RN_WITH_PARTITIONBY
  FROM [Chinook].[dbo].[Track]
 -- WHERE Composer IS NOT NULL