
USE BikeStores;

WITH TOTAL AS(
	SELECT 
	 PP.CategoryID CATEGORIA
	,COUNT(*) PRODUTOS_TOTAIS
	
FROM Production.Product  PP
GROUP BY PP.CategoryID
)
SELECT 
	 PP.CategoryID CATEGORIA
	,PP.BrandID BRAND
	,COUNT(*) PRODUTOS_TOTAIS
	,T.PRODUTOS_TOTAIS
	,CAST(COUNT(*)*1.0/ SUM(COUNT(*)) OVER(PARTITION BY CategoryID) * 100 AS DECIMAL(4,2)) PERCENTUAL_DO_TOTAL
	
FROM Production.Product  PP
INNER JOIN TOTAL T ON T.CATEGORIA = PP.CategoryID
GROUP BY PP.CategoryID, PP.BrandID ,T.PRODUTOS_TOTAIS;



-- AGREGAÇÃO COM CTE
WITH CATEGORIA_TOTAL (CATEGORIA, BRAND, PRODUTOS_TOTAIS)AS
(
	SELECT 
		 PP.CategoryID CATEGORIA
		,PP.BrandID BRAND
		,COUNT(*) PRODUTOS_TOTAIS
	
	FROM Production.Product  PP
	GROUP BY PP.BrandID,PP.CategoryID
)
SELECT 
	 *
	,SUM(PRODUTOS_TOTAIS) OVER(PARTITION BY CATEGORIA) AS TOTAL_POR_CATEGORIA
	,CAST(PRODUTOS_TOTAIS * 100.0 / SUM(PRODUTOS_TOTAIS) OVER(PARTITION BY CATEGORIA) AS DECIMAL(4, 1)) PORCENTAGEM_DO_TOTAL
	--,PRODUTOS_TOTAIS * 100.0 / SUM(PRODUTOS_TOTAIS) OVER(PARTITION BY CATEGORIA) PORCENTAGEM_DO_TOTAL
FROM CATEGORIA_TOTAL
