
USE BikeStores;



SELECT
	 PP.CategoryID CATEGORIA
	,PP.BrandID BRAND
	,PP.ProductID ID_PRODUTO
	,PP.Name NOME
	,COUNT(*) OVER(PARTITION BY BrandID) TOTAL_PRODUTOS_BRAND
	,SUM(PP.ListPrice) OVER(PARTITION BY CategoryID) PRECO_TOTAL_CATEGORIA
	,AVG(PP.ListPrice) OVER(PARTITION BY BrandID) MEDIA_PRECO_BRAND
	,MIN(PP.ListPrice) OVER(PARTITION BY CategoryID) MENOR_PRECO_CATEGORIA
FROM Production.Product PP 
WHERE CategoryID IN (1, 2, 3)
ORDER BY CATEGORIA