

USE ContosoRetailDW;


WITH TABELA_VENDAS_TOTAIS(ANO, MES, VENDAS) AS
(
SELECT TOP 100
	 DATEPART(YEAR ,FOS.DateKey) ANO
	,DATEPART(MONTH ,FOS.DateKey) MES
	,SUM(FOS.SalesAmount) VENDAS

FROM FactOnlineSales FOS
INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
GROUP BY DATEPART(YEAR ,FOS.DateKey), DATEPART(MONTH ,FOS.DateKey)
)
SELECT 
	 ANO
	,MES
	
	,FORMAT(VENDAS, 'C0') VENDAS
	,FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO ORDER BY MES),'C0') VENDA_MENSAL_ACUMULADA
	,FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO),'C0') VENDA_ANUAL

FROM TABELA_VENDAS_TOTAIS
ORDER BY ANO, MES