

USE ContosoRetailDW;


WITH TABELA_VENDAS_TOTAIS(ANO, MES, VENDAS) AS
(
SELECT TOP 100
	 DATEPART(YEAR ,FOS.DateKey) ANO
	,DATEPART(MONTH ,FOS.DateKey) MES
	,SUM(FOS.SalesAmount) VENDAS

FROM FactOnlineSales FOS
INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
GROUP BY DATEPART(YEAR ,FOS.DateKey), DATEPART(MONTH ,FOS.DateKey)
)
SELECT 
	 ANO
	,MES
	
	,FORMAT(VENDAS, 'C0') VENDAS
	,FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO ORDER BY MES),'C0') VENDA_MENSAL_ACUMULADA
	,FORMAT(SUM(VENDAS) OVER(ORDER BY ANO ASC
						ROWS BETWEEN UNBOUNDED PRECEDING 
						AND CURRENT ROW), 'C0') AS VENDA_ACUMULADA_ANO
	,FORMAT(AVG(VENDAS) OVER(PARTITION BY ANO ORDER BY ANO ASC
						ROWS BETWEEN UNBOUNDED PRECEDING --LINHAS ANTERIORES DENTRO DA PARTIÇÃO
						AND	CURRENT ROW), 'C0') AS VENDA_AVG
	,FORMAT(AVG(VENDAS) OVER(ORDER BY ANO, MES ASC
						ROWS BETWEEN 6 PRECEDING AND -- 6 LINHAS ANTERIORES
						1 PRECEDING -- 1 LINHA ANTERIOR
						), 'C0') AS VENDA_MOVEL_6M

FROM TABELA_VENDAS_TOTAIS
ORDER BY ANO, MES