
USE ContosoRetailDW;


WITH TABELA_VENDAS_TOTAIS(ANO, MES, VENDAS) AS
(
SELECT
	 DATEPART(YEAR ,FOS.DateKey) ANO
	,DATEPART(MONTH ,FOS.DateKey) MES
	,SUM(FOS.SalesAmount) VENDAS

FROM FactOnlineSales FOS
INNER JOIN DimProduct DP ON DP.ProductKey = FOS.ProductKey
GROUP BY DATEPART(YEAR ,FOS.DateKey), DATEPART(MONTH ,FOS.DateKey)
)
SELECT 
	 ANO
	,MES	
	,FORMAT(VENDAS, 'C0') VENDAS
	--LAG(COLUNA, QUANT DE MESES ANTERIORES, VALOR RETORNADO CASO NÃO TENHA MESES ANTES)
	,LAG(VENDAS,2, 5)OVER(PARTITION BY ANO ORDER BY ANO, MES) MES_ANTERIOR
	,LEAD(VENDAS, 6, 10)OVER(PARTITION BY ANO ORDER BY ANO, MES) MES_POSTERIOR

FROM TABELA_VENDAS_TOTAIS
ORDER BY ANO, MES


--#######################################################


USE BikeStores

SELECT
	 SC.CustomerID
	,SC.FirstName
	,SC.StateOrRegion
	,SO.OrderID
	,LAG(SO.OrderID, 2, 0)OVER(PARTITION BY SC.CustomerID ORDER BY SO.OrderID) ULTIMO_PEDIDO
FROM Sales.Customer SC
INNER JOIN Sales.[Order] SO ON  SC.CustomerID = SO.CustomerID 
ORDER BY SC.CustomerID